---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: app-with-chart
  namespace: flux-system
spec:
  image: ghcr.io/satr/app-with-chart
  interval: 1m0s
  secretRef:
    name: regcred

