---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app-with-chart
  namespace: app-with-chart
spec:
  filterTags:
    pattern: ^main-[a-f0-9]+-(?P<ts>[0-9]+)
    extract: $ts
  imageRepositoryRef:
    name: app-with-chart
  policy:
    numerical:
      order: asc

