---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app-with-chart
  namespace: app-with-chart
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/equinor/app-with-chart
  ignore: |
    .git/
    .sops.yaml
    .gitlab-ci.yml

